### ISSUE TITLE
hq: editor VMs not connecting production storage nfs share on boot

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-local#283]
Production storage for ddr editor VMs in HQ is located on an nfs share which should be mounted through an entry in `/etc/fstab` but share fails to mount automatically at boot as expected.  Invoking `mount -a` will connect the share successfully.

The VMs are deb10 running on Virtualbox (v.??). This behavior does not occur on other deb10 VMs running on the HQ VMware ESXi infrastructure.

Possible remeditation: 

https://unix.stackexchange.com/questions/530900/etc-fstab-does-not-mount-automatically-on-debian-10

**Comment by pkikawa** [comment]
virbox 6.0.20 r137117

**Comment by GeoffFroh** [comment]
Try adding:

`x-systemd.after=network-online.target` 

To the nfs mount options in `/etc/fstab`

E.g.,

`x-systemd.after=network-online.target,tcp,nolock,intr`

See: 
https://unix.stackexchange.com/questions/349264/fstab-mount-wait-for-network
https://www.freedesktop.org/software/systemd/man/systemd.mount.html

(In addition, recommended Qumulo mount options are discussed here: 
https://care.qumulo.com/hc/en-us/articles/115008111268-Recommended-NFS-Mount-Options
)

**Comment by GeoffFroh** [comment]
Another possibility would be to use `systemd` natively to do the mount; see article here:

https://blog.tomecek.net/post/automount-with-systemd/

IMPORTANT:

- Remove the existing mount from `/etc/fstab`
- Use the files from this gist https://gist.github.com/GeoffFroh/a2fb9ed217e5bd25114ffe1f634f439a; YOU MUST USE THE FILENAMES (`media-qnfs.mount` and `media-qnfs.automount`)
