### ISSUE TITLE
kombu serialization errors with collection creation and *any* edit/save operations (objects & collections) (dana's local vm)

### ISSUE THREAD

**Issue by pkikawa** [denshoproject/ddr-local#289]
[danatset.zip](https://github.com/denshoproject/ddr-local/files/4969411/danatset.zip)

getting failure msgs on edit / creation jobs. edits are successful and objects/collection is created

running on 5.0.11 deb 10 

the above failures are from creating an collection (which threw the failure msg but was correctly created, and editing collection info (threw failure msg but was correctly created)

i have been able to successfully edit collections and objects after the fact. failures have been consistent so far

**Comment by pkikawa** [comment]
[danahtmls.zip](https://github.com/denshoproject/ddr-local/files/4969618/danahtmls.zip)

this is on ddr-testing-40383. have only been able to replicate on dana's local vm

**Comment by pkikawa** [comment]
seeing this only on dana's local vm, not on any others

**Comment by GeoffFroh** [comment]
The virtual environment could be out-of-sync with production. Try `rm -rf`-ing the `venv` directory in `ddr-local`, then re-running `make install`

**Comment by pkikawa** [comment]
git.log

commit 3410d59fb651d7b23b8cdc1eb976510617602bf8
Author: Philip Kikawa <philip.kikawa@densho.org>
Date:   Wed Jul 22 15:08:13 2020 -0700

    Updated metadata file(s)

    @agent: ddr-local

commit 7e3439f6bc77473ea3783cfe208abb7299d5d430
Author: Philip Kikawa <philip.kikawa@densho.org>
Date:   Wed Jul 22 15:01:43 2020 -0700

    Updated entity file(s)

    @agent: ddr-local

commit b610c2608fc65c61077cd56aa4a46d9b92fd80e3
Author: Philip Kikawa <philip.kikawa@densho.org>
Date:   Wed Jul 22 15:01:43 2020 -0700

    Initialized entity ddr-testing-40383-1

    @agent: ddr-local

commit 1eac737639ca8c003e37859b7b1e923068e0460b
Author: Philip Kikawa <philip.kikawa@densho.org>
Date:   Wed Jul 22 15:01:21 2020 -0700

    Initialized collection ddr-testing-40383

    @agent: ddr-local

**Comment by pkikawa** [comment]
[ddr-testing-40180-1.zip](https://github.com/denshoproject/ddr-local/files/4974310/ddr-testing-40180-1.zip)

testing collection from which these errors have been thrown from.

**Comment by gjost** [comment]
Check the various places where tasks are sent to Celery AND where responses are sent back to Celery.  Check for non-str values, especially for pathlib.Path objects.

Seealso https://github.com/denshoproject/ddr-local/issues/287

**Comment by pkikawa** [comment]
rebuilding the venv resolved the issue
