### ISSUE TITLE
Sorting TypeError in ddr-densho-1000-485

### ISSUE THREAD

**Issue by gjost** [denshoproject/ddr-local#303]
Problem encountered while building list to display tabs of Entity children types.
`'<' not supported between instances of 'int' and 'str'` while trying to compare
- `<DDR.models.entity.Entity segment:ddr-densho-1000-485-1>` and
-  `<DDR.models.entity.Entity segment:ddr-densho-1000-485-2>`

Error occurred with `ddrlocal` `v5.2.6` running in a VirtualBox VM.

[ddr-densho-1000-485-TypeError at _ui_entity.zip](https://github.com/denshoproject/ddr-local/files/8050508/ddr-densho-1000-485-TypeError.at._ui_entity.zip)

**Comment by gjost** [comment]
I was able to duplicate this on my local dev VM running `ddrlocal` `v5.2.6` with a `ddr-densho-1000` cloned from the Gitolite hub.

**Comment by GeoffFroh** [comment]
@sarabeckman and/or @pkikawa: please verify and close
