### ISSUE TITLE
Add support for .zip, .docx, .xlsx and other productivity file types

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-local#304]
Archivists need to be able to add their background notes and docs to the collection repos to preserve information about their work in researching and processing the materials. These documents are often produced in Word, Excel and other Office apps. They might also be a collection of documents compressed into a single zipfile. 

They currently use the "Administrative" file type to upload PDF release forms; the Editor application should allow these other formats as well.

**Comment by gjost** [comment]
Fired up my dev copy of DDR and fed it a couple office productivity files:
- 2021-GeoffJost-DenshoPerformanceEvaluationForm.docx
- 2022 Time Tracking - GJ.xlsx

Coming up with metadata to describe these was the hardest part. Yeah.
Ingest worked fine, no errors.
No access files were created. The UI displays URLs for them anyway but these don't work.
No thumbnails are displayed in list views.  I'm sure there's a way to generate them.
Download links work and the documents open just fine in LibreOffice.
- ddr-testing-40396-1-administrative-352415cdf3.docx
- ddr-testing-40396-1-administrative-eb7ee35037.xlsx

**Comment by GeoffFroh** [comment]
Test comment....

**Comment by GeoffFroh** [comment]
Let's use the same file icon as the HTML type files for the thumbnail in SORL.
