### ISSUE TITLE
DDR user does not have access to sf_ddrshared

### ISSUE THREAD

**Issue by pkikawa** [denshoproject/ddr-local#305]
current perms for sf_ddrshared: 

drwxrwx---  1  root  vboxsf

this is on a vm that i created on my home desktop, set `sf_ddrshared` perms with chmod 770 - then booted up at the HQ. currently only the root user has perms to view the contents of sf_ddrshared - ddr user does not. 

also the ddr venv does not launch when su'ing to ddr

debian 11
virtualbox 6.1.32

**Comment by gjost** [comment]
Is it possible that the Virtulbox Guest Additions were not installed?  I did a test install this morning and the `/media/sf_ddrshared` did not appear until I had installed guest additions.

Also, is the non-root user you're using part of the `vboxsf` group?  There is a task in `ddr-cmdln/Makefile` that adds the `ddr` user to this group but it doesn't do anything to the `densho` user or anybody else.

**Comment by gjost** [comment]
Note that the `ddr-user` task is run several steps after the `ddrlocal-master` package is run.

**Comment by pkikawa** [comment]
Virtualbox Guest Additions is installed (followed the standard install steps w/o issue.

i was trying to access the `sf_ddrshared` folder with the `ddr `user.

**Comment by gjost** [comment]
Can you confirm that `ddr` is in the `vboxsf` group? (run `cat /etc/group|grep vboxsf`)

**Comment by pkikawa** [comment]
`cat /etc/group|grep vboxsf`
`vboxsf:x:998:`

**Comment by gjost** [comment]
Please add `ddr` to the `vboxsf` group and let me know if it works.  You can do this one of two ways:
- Install `ddrlocal-master`, `cd /opt/ddr-local`, and then `sudo make ddr-user`
- Edit `/etc/group` and add `ddr` to the `vboxsf` line so it looks like this: `vboxsf:x:998:ddr` (i.e. add `ddr` after the final `:`).

**Comment by pkikawa** [comment]
`make ddr-user` worked - not sure why it didn't work the first time i ran it during the initial install. 

ddr venv is also now automatically activating when switching to ddr user.

**Comment by gjost** [comment]
Cosmic rays? Phase of the moon?  Let me know if it happens again.

**Comment by pkikawa** [comment]
who knows lol. gonna close this one out
