### ISSUE TITLE
Character limit in Persons field

### ISSUE THREAD

**Issue by sarabeckman** [denshoproject/ddr-local#326]
When using the Editor UI there is a character limit of 4,000 characters.  

Dina added a name list  to ddr-densho-97-248 and it fit within the character limit, saved and checked it to make sure all of them were there.   Editor reformatted to add "namepart:" which then pushed it over the 4000 character limit. So object metadata looks fine, but if you go to object metadata edit, it has an error message for being over character limit.

**Comment by GeoffFroh** [comment]
This is related to character limits set in `ddr-defs`. @gjost believes that this may be an issue that *only* applies for the DDR Editor webui. 

@sarabeckman will confirm by trying to do a batch update through the ddr command line interface to see what happens.

**Comment by sarabeckman** [comment]
Dina create entity csv with list of names in person field with more than 4,000 characters. I imported csv to ddr-densho-97-101 successfully.

**Comment by gjost** [comment]
I tried just commenting out the `max_length` for all the text-box fields in the Entity model.  Everything still works and I was able to paste a 5000-char block of text into `persons`.  Requires changing `ddr-defs`

**Comment by GeoffFroh** [comment]
Fix is ready in code; but needs to be committed then deployed for testing

**Comment by gjost** [comment]
Fixed in `ddr-defs` branch `fix-326-textarea-char-limit` commit `07b938d` and merged in to `develop` and `master`.
