### ISSUE TITLE
Users should be able to see all of their Collections/Entities, whether on the attached USB drive or not

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-local#62]
Currently, users can only see collection repos that are contained on the USB drive directly attached to the VM. However, they may need to edit collections that have already been sent to Densho HQ. There needs to be a way to access all collections belonging to the partner through the web UI. The UI should:
- be browseable/searchable
- indicate whether the collections are local (on the usb drive) or at Densho
- allow editing of collections/entities
- allow for download (or maybe request) of master/mezz binaries

The primary use case for this is editing the metadata, rather than the binaries (files) associated with a particular collection.

**Comment by gjost** [comment]
see Inventory https://github.com/densho/ddr-local/issues/99
